/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer User
 */
public class SuperStringSoftware extends javax.swing.JFrame {

    /**
     * Creates new form SuperStringSoftware
     */
    public SuperStringSoftware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        btnLength = new javax.swing.JButton();
        txtLength = new javax.swing.JTextField();
        lblLengthValue = new javax.swing.JLabel();
        lblCaps = new javax.swing.JLabel();
        txtCaps = new javax.swing.JTextField();
        btnCaps = new javax.swing.JButton();
        lblCapsValue = new javax.swing.JLabel();
        lbl4th = new javax.swing.JLabel();
        txt4th = new javax.swing.JTextField();
        btn4th = new javax.swing.JButton();
        lbl4thValue = new javax.swing.JLabel();
        lblIdentical = new javax.swing.JLabel();
        txtIdentical1 = new javax.swing.JTextField();
        btnIdentical = new javax.swing.JButton();
        lblIdenticalValue = new javax.swing.JLabel();
        lbl4To6 = new javax.swing.JLabel();
        txt4To6 = new javax.swing.JTextField();
        btn4To = new javax.swing.JButton();
        lbl4To6Value = new javax.swing.JLabel();
        lblReplace = new javax.swing.JLabel();
        txtReplace = new javax.swing.JTextField();
        btnReplace = new javax.swing.JButton();
        lblReplaceValue = new javax.swing.JLabel();
        lblFound = new javax.swing.JLabel();
        txtFound = new javax.swing.JTextField();
        btnFound = new javax.swing.JButton();
        lblFoundValue = new javax.swing.JLabel();
        txtFoundLetter = new javax.swing.JTextField();
        txtIdentical2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Super String Software ");

        lblLength.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLength.setText("Enter a string. The program will output the  number of characters in the string. ");

        btnLength.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLength.setText("Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        txtLength.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLengthActionPerformed(evt);
            }
        });

        lblLengthValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLengthValue.setText("   ....");

        lblCaps.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCaps.setText("Enter a string using lowercase letters. The program will output  the string in all capital letters. ");

        txtCaps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnCaps.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCaps.setText("All caps");
        btnCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapsActionPerformed(evt);
            }
        });

        lblCapsValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCapsValue.setText("   ....");

        lbl4th.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl4th.setText("Enter a string. The program will output the character at 4th spot. ");

        txt4th.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn4th.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4th.setText("4th spot");
        btn4th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4thActionPerformed(evt);
            }
        });

        lbl4thValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl4thValue.setText("   ....");

        lblIdentical.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIdentical.setText("Enter two strings. The program will output wether or not they are identical.");

        txtIdentical1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnIdentical.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIdentical.setText("identical");
        btnIdentical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdenticalActionPerformed(evt);
            }
        });

        lblIdenticalValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIdenticalValue.setText("   ....");

        lbl4To6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl4To6.setText("Enter a string that is atleast 8 charaters long. The program will output the characters 4 to 6");

        txt4To6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn4To.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn4To.setText("characters 4 o 6");
        btn4To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ToActionPerformed(evt);
            }
        });

        lbl4To6Value.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl4To6Value.setText("   ....");

        lblReplace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblReplace.setText("Enter a string that containt at last one \"a\". The program will then replace all occurences of letter \"a\" with \"x\"");

        txtReplace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnReplace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReplace.setText("Replaces \"a\"");
        btnReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceActionPerformed(evt);
            }
        });

        lblReplaceValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblReplaceValue.setText("   ....");

        lblFound.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFound.setText("Enter a string and a letter. The program will output whether or not the letter is found in the String.");

        txtFound.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoundActionPerformed(evt);
            }
        });

        btnFound.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFound.setText("Letter found?");
        btnFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoundActionPerformed(evt);
            }
        });

        lblFoundValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFoundValue.setText("   ....");

        txtFoundLetter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtIdentical2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl4To6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblReplace, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(txt4To6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn4To)
                            .addGap(69, 69, 69)
                            .addComponent(lbl4To6Value, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReplace)
                            .addGap(310, 310, 310))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(txtFound, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFoundLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFound)
                            .addGap(101, 101, 101)
                            .addComponent(lblFoundValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(229, 229, 229)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(lblLength))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLength)
                            .addGap(98, 98, 98)
                            .addComponent(lblLengthValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(115, 115, 115))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblCaps, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdentical, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl4th, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(83, 83, 83)
                                            .addComponent(txtCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCaps))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(74, 74, 74)
                                            .addComponent(txt4th, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn4th)))
                                    .addGap(106, 106, 106)
                                    .addComponent(lblCapsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbl4thValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(126, 126, 126)
                                    .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIdentical)
                                    .addGap(111, 111, 111)
                                    .addComponent(lblIdenticalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(116, 116, 116)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblReplaceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFound))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(lblLength)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLength)
                            .addComponent(lblLengthValue))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(lblCaps)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaps)
                    .addComponent(lblCapsValue)
                    .addComponent(txtCaps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lbl4th)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4th)
                    .addComponent(txt4th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4thValue))
                .addGap(18, 18, 18)
                .addComponent(lblIdentical)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnIdentical))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdenticalValue)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(37, 37, 37)
                .addComponent(lbl4To6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4To)
                        .addComponent(lbl4To6Value))
                    .addComponent(txt4To6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblReplace)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReplace)
                        .addComponent(lblReplaceValue))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblFound)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFoundLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFound)
                            .addComponent(lblFoundValue))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIdenticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdenticalActionPerformed
        // TODO add your handling code here:
        String value1 = txtIdentical1.getText();
        String value2 = txtIdentical2.getText();
        boolean flag = value1.equals(value2);
        lblIdenticalValue.setText(String.valueOf(flag));

    }//GEN-LAST:event_btnIdenticalActionPerformed

    private void btnFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoundActionPerformed
        // TODO add your handling code here:
        String value1 = txtFound.getText();
        String value2 = txtFoundLetter.getText();
        int num = value1.indexOf(value2);
        lblFoundValue.setText(String.valueOf(num));
    }//GEN-LAST:event_btnFoundActionPerformed

    private void txtFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoundActionPerformed

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
        // TODO add your handling code here:
        String value = txtLength.getText();
        value =   value.trim();
        int length = value.length();
        lblLengthValue.setText(String.valueOf(length));
        

       
      
        
      

    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapsActionPerformed
        // TODO add your handling code here:
        String value = txtCaps.getText();
        value = value.toUpperCase();
        lblCapsValue.setText(value);
    }//GEN-LAST:event_btnCapsActionPerformed

    private void btn4thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4thActionPerformed
        // TODO add your handling code here:
        String value = txt4th.getText();
        char C = value.charAt(4);
        lbl4thValue.setText(String.valueOf(C));
    }//GEN-LAST:event_btn4thActionPerformed

    private void btn4ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ToActionPerformed
        // TODO add your handling code here:
        String value = txt4To6.getText();
        value = value.substring(4, 7); 
        lbl4To6Value.setText(value);
    }//GEN-LAST:event_btn4ToActionPerformed

    private void btnReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceActionPerformed
        // TODO add your handling code here:
        String value = txtReplace.getText();
        value = value.replace("a","x");
        lblReplaceValue.setText(value);
    }//GEN-LAST:event_btnReplaceActionPerformed

    private void txtLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLengthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperStringSoftware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn4To;
    private javax.swing.JButton btn4th;
    private javax.swing.JButton btnCaps;
    private javax.swing.JButton btnFound;
    private javax.swing.JButton btnIdentical;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnReplace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl4To6;
    private javax.swing.JLabel lbl4To6Value;
    private javax.swing.JLabel lbl4th;
    private javax.swing.JLabel lbl4thValue;
    private javax.swing.JLabel lblCaps;
    private javax.swing.JLabel lblCapsValue;
    private javax.swing.JLabel lblFound;
    private javax.swing.JLabel lblFoundValue;
    private javax.swing.JLabel lblIdentical;
    private javax.swing.JLabel lblIdenticalValue;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblLengthValue;
    private javax.swing.JLabel lblReplace;
    private javax.swing.JLabel lblReplaceValue;
    private javax.swing.JTextField txt4To6;
    private javax.swing.JTextField txt4th;
    private javax.swing.JTextField txtCaps;
    private javax.swing.JTextField txtFound;
    private javax.swing.JTextField txtFoundLetter;
    private javax.swing.JTextField txtIdentical1;
    private javax.swing.JTextField txtIdentical2;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtReplace;
    // End of variables declaration//GEN-END:variables
}
